CREATE OR REPLACE VIEW `meli-bi-data.EXPLOTACION.BT_MKP_COUPON_ORDER`
OPTIONS (
    friendly_name = "BT_MKP_COUPON_ORDER",
    description = "Vista desnormalizada con todas las ordenes de compra para cada COUPON_ID",
    labels = [("bu","marketplace"),("track","cupones")]
) AS
SELECT
    COUPON_ID,
    COUPON_NAME,
    ORDERS.ORD_ORDER_ID,
    ORDERS.ORD_STATUS,
    ORDERS.ORD_CLOSED_DT,
    SIT_SITE_ID,
    ORDERS.ITEM_ID AS ITE_ITEM_ID,
    ORDERS.ITEM_VARIATION AS ITE_VAR_ID,
    ORDERS.PARTY_TYPE_ID,
    ORDERS.CUS_CUST_ID_SEL,
    ORDERS.QTY AS ORD_QTY,
    ORDERS.UNIT_PRICE AS ORD_UNIT_PRICE,
    ORDERS.TOTAL_AMOUNT AS ORD_TOTAL_AMOUNT,
    MKT_CAMPAIGN_TOKEN_ID,
    PROMOTIONS_CAMPAIGN_ID,
    ORDERS.COU_ORD_ORIGINAL_AMOUNT,
    ORDERS.COU_ORD_REFUNDED_AMOUNT,
    ORDERS.COU_SHARE
FROM `meli-bi-data.EXPLOTACION.BT_MKT_COUPON`
LEFT JOIN UNNEST(ORDERS) AS ORDERS
